- name: Check if node_exporter is installed
  ansible.builtin.stat:
    path: "/opt/node_exporter/node_exporter"
  register: __node_exporter_is_installed
- name: Gather currently installed node_exporter version (if any)
  ansible.builtin.command: "/opt/node_exporter/node_exporter --version | grep -o ' [0-9]*\\.[0-9]*\\.[0-9]*' | cut -c2-"
  changed_when: false
  register: __node_exporter_current_version_output
  when: __node_exporter_is_installed.stat.exists
- name: Create node_exporter group
  ansible.builtin.group:
    name: "node_exporter"
    state: present
    system: true
- name: Create node_exporter user
  ansible.builtin.user:
    name: "node_exporter"
    groups: "node_exporter"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
- name: Create node_exporter directory
  ansible.builtin.file:
    path: "/opt/node_exporter"
    state: directory
    mode: "0755"
- name: Install node_exporter
  block:
    - name: Get node_exporter binary checksum
      block:
        - name: Get checksum list from github
          ansible.builtin.set_fact:
            __node_exporter_checksums: "{{ lookup('url', 'https://github.com/prometheus/node_exporter/releases/download/v' + node_exporter.version + '/sha256sums.txt', wantlist=True) | list }}"
          run_once: true
          until: __node_exporter_checksums is search('linux-' + go_arch + '.tar.gz')
          retries: 10
        - name: "Get checksum for {{ go_arch }}"
          ansible.builtin.set_fact:
            __node_exporter_checksum: "{{ item.split(' ')[0] }}"
          with_items: "{{ __node_exporter_checksums }}"
          when:
            - "('linux-' + go_arch + '.tar.gz') in item"
    - name: Download node_exporter binary to local folder
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter.version }}/node_exporter-{{ node_exporter.version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp/node_exporter-{{ node_exporter.version }}.linux-{{ go_arch }}.tar.gz"
        checksum: "sha256:{{ __node_exporter_checksum }}"
        mode: "0644"
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false
    - name: Unpack node_exporter binary
      ansible.builtin.unarchive:
        src: "/tmp/node_exporter-{{ node_exporter.version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/node_exporter-{{ node_exporter.version }}.linux-{{ go_arch }}/node_exporter"
      delegate_to: localhost
      check_mode: false
    - name: Propagate node_exporter binaries
      ansible.builtin.copy:
        src: "/tmp/node_exporter-{{ node_exporter.version }}.linux-{{ go_arch }}/node_exporter"
        dest: "/opt/node_exporter/node_exporter"
        owner: node_exporter
        group: node_exporter
        mode: 0755
        force: true
      notify: restart node_exporter
      when: not ansible_check_mode
  when: not __node_exporter_is_installed.stat.exists or __node_exporter_current_version_output != node_exporter.version
- name: Gather package facts
  ansible.builtin.package_facts:
- name: Gather service facts
  ansible.builtin.service_facts:
- name: Copy the node_exporter systemd service file
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart node_exporter
- name: Create node_exporter config directory
  ansible.builtin.file:
    path: "/etc/node_exporter"
    state: directory
    owner: root
    group: root
    mode: u+rwX,g+rwX,o=rX
- name: Copy the node_exporter config file
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/node_exporter/config.yaml
    owner: root
    group: root
    mode: "0644"
  notify: restart node_exporter
- name: Enable & Start Node Exporter service
  ansible.builtin.service:
    name: node_exporter
    enabled: true
    state: started
