---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    docker:
      metrics:
        enabled: false
      autoheal:
        enabled: true
        schedule: "*/2 * * * *"
        include_exited: true
  roles:
    - role: docker
