#!/bin/bash +e
# Source: https://raw.githubusercontent.com/daniel7grant/dx

if [[ "$#" -eq 1 ]] ; then
    /usr/bin/docker exec -it $1 sh -c '$( sh -c "getent passwd root | cut -d: -f7" )'   
else
    /usr/bin/docker exec $@
fi
