- name: Set Hostname
  ansible.builtin.hostname:
    name: "{{ hostname | default(inventory_hostname) }}"
- name: Update hosts file
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
- name: Update MOTD contents
  ansible.builtin.copy:
    dest: /etc/motd
    content: "{{ system.motd | default('') }}"
- name: Update timezone
  community.general.timezone:
    name: "{{ system.timezone | default('UTC') }}"
- name: Update swappiness
  ansible.builtin.sysctl:
    name: vm.swappiness
    value: "{{ system.swappiness | default(10) }}"
    state: present
    reload: true
- name: Ensure base packages are installed
  ansible.builtin.package:
    name:
      - sudo
      - curl
      - vim
      - restic
    state: latest
