- name: Set Hostname
  ansible.builtin.hostname:
    name: "{{ hostname | default(inventory_hostname) }}"
    use: generic
- name: Update hosts file
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "# {mark} normalize"
    block: |
      127.0.0.1 localhost {{ hostname | default(inventory_hostname + " " + inventory_hostname_short) }}

      ::1 localhost ip6-localhost ip6-loopback {{ hostname | default(inventory_hostname + " " + inventory_hostname_short) }}
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
- name: Update MOTD contents
  ansible.builtin.copy:
    dest: /etc/motd
    content: "{{ system.motd | default('') }}"
- name: Update timezone
  community.general.timezone:
    name: "{{ system.timezone | default('UTC') }}"
- name: Update swappiness
  ansible.builtin.sysctl:
    name: vm.swappiness
    value: "{{ system.swappiness | default(10) }}"
    state: present
    reload: true
- name: Ensure base packages are installed
  ansible.builtin.package:
    name:
      - sudo
      - curl
      - vim
      - restic
    state: latest
