---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install cron
      ansible.builtin.apt:
        name: cron
        state: present
