- name: Install wireguard
  ansible.builtin.apt:
    name: wireguard
    state: latest
    update_cache: true
- name: Ensure wireguard directory exists
  ansible.builtin.file:
    path: /etc/wireguard
    state: directory
    owner: root
    group: root
    mode: "0700"
- name: Configure wireguard interface {{ item.key }}
  ansible.builtin.include_tasks: interface.yml
  vars:
    wg_iface_name: "{{ item.key }}"
    wg_iface: "{{ item.value }}"
  loop: "{{ wireguard.interfaces | dict2items }}"
  when: inventory_hostname in (item.value.nodes | default({}))
