---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    auto_upgrades:
      reboot:
        enabled: false
        time: "02:00"
      security: true
      updates: false
      backports: false
      major: false
      packages:
        exclude: []
      cleanup: true
  roles:
    - role: auto_upgrades
