---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    traefik:
      enabled: true
      container_name: traefik
      metrics:
        enabled: false
      cert_dumper:
        enabled: false
  roles:
    - role: traefik
